config/routes.rb
Rails.application.routes.draw do

  get '/portfolio' => 'pages#portfolio'
  get '/about'=> 'pages#about'
  get '/blog' => 'pages#blog'

  root 'pages#welcome'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

def welcome
end

def portfolio
end

def blog
end

def about
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300italic,500,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

</head>
<body>
<div class="header">
    <div class="container">

        <h1>Elise Fitzgerald</h1>

        <div class="navigation">
            <ul>
                <li><%= link_to "Welcome", root_path(@welcome) %></li>
                <li><%= link_to "Portfolio", portfolio_path(@portfolio) %></li>
                <li><%= link_to "Blog", "https://medium.com/@elisefitzgerald" %></li>
                <li><%= link_to "About", about_path(@about) %></li>
                <li>Contact</li>
            </ul>
        </div>

    </div>
</div>

<%= yield %>

<div class="footer">
    <div class="container">
        <ul>
            <li><%=link_to image_tag("github7.png"), url_for("https://github.com/EliseFitz15") %></li>
            <li><%=link_to image_tag("linkedin1.png"), url_for("https://www.linkedin.com/in/elisefitzgerald15") %></li>
            <li><%=link_to image_tag("twitter12.png"), url_for("https://twitter.com/ENFitzgerald15") %></li>
        </ul>
        <p>&#169 2015 Elise Fitzgerald</p>
    </div>
</div>

</body>
</html>

app/views/pages/about.html.erb
<div class="about">
  <div class="container">


    <div class="headshot">
      <div class="col-md-5" align="center"><%=link_to image_tag("headshot2.png") %>
    </div>

    <div class="bio">
      <div class="col-md-6" align="center">
        <h1>Hello!</h1>
        <p>Nice to meet you!
          <br>
          <p>Hi, thanks for stopping by. I am an aspiring Ruby on Rails developer and attending Launch Academy
          to advance my learning. I have been coding for about 6 months and have learned some basics in Javascript,
          jQuery, HTML, CSS, Ruby on Rails and AngularJS.</p>
          <br>
          <p>Previously, I spent 5+ years as a public relations professional with experience integrated, strategic
          communications campaigns across public affairs, consumer and technology industries. I hope to bring my passion
          for communications and strategy to a career in web development. I am excited to continue learning and share the experience
          with you at the blog listed above. </p>
    </div>
  </div>
</div>

app/views/pages/portfolio.html.erb
  </div>

<div class="projects">
    <div class="container">


    <div class="navs">
      <ul class="nav nav-pills">
            <li class="nav-angular"><a href="#">AngularJS</a></li>
            <li class="nav-rails"><a href="#">Ruby on Rails</a></li>
            <li class="nav-jquery"><a href="#" >JavaScript</a></li>
        </ul>
    </div>

    <div class="row">
        <div class="col-md-4">
            <a class="angular thumbnail">
              <%= image_tag "Outbox.PNG" %>
            </a>
            <a class="title" href= "#">Outbox</a>
            <p class="description"></p>
          </div>
          <div class="col-md-4">
            <a class="rails thumbnail">
              <%= image_tag "Innovation.PNG" %>
            </a>
            <a class="title" href= "#">Innovation Cloud</a>
            <p class="description"></p>
          </div>
          <div class="col-md-4">
            <a class="jquery thumbnail">
              <%= image_tag "Threadlyjq.PNG" %>
            </a>
            <a class="title" href= "#">Threadly</a>
            <p class="description"></p>
          </div>
    </div>

    <div cgitlass="row">
        <div class="col-md-4">
            <a class="jquery thumbnail">
              <%= image_tag "Bonsijq.PNG" %>
            </a>
            <a class="title" href= "#">Bonsai Meme Generator</a>
            <p class="description"></p>
          </div>
          <div class="col-md-4">
            <a class="angular thumbnail">
              <%= image_tag "boltang.PNG" %>
            </a>
            <a class="title" href= "#">Bolt Network</a>
            <p class="description"></p>
          </div>
          <div class="col-md-4">
            <a class="rails thumbnail">
              <%= image_tag "readmerails.PNG" %>
            </a>
            <a class="title" href= "#">Read Me</a>
            <p class="description"></p>
          </div>
    </div>
    </div>
</div>

app/views/pages/welcome.html.erb
<div class="main">
    <div class="container">
        <h1>Hi I'm <span>Elise.</span> <br>I tell stories & <br> build websites.</h1>
       <div class="btn">
           <p><%= link_to "View My Work", portfolio_path(@portfolio) %></p>

        </div>
    </div>
</div>